# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0002_art_medium'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='description',
            field=models.TextField(default='Coming Soon'),
        ),
    ]
