# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0003_art_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='img_url',
            field=models.ImageField(upload_to=''),
        ),
    ]
