# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 16:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('art', '0005_auto_20161216_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='art',
            name='description',
            field=models.CharField(default='Coming Soon', max_length=500),
        ),
        migrations.AlterField(
            model_name='art',
            name='img_url',
            field=models.ImageField(upload_to='gallery'),
        ),
    ]
